name: Deploy Portfolio to EC2

on:
  push:
    branches:
      - main

env:
  PUBLIC_IP: 3.110.77.19
  EC2_USER: ubuntu
  SSH_PORT: 1243

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure SSH key
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ env.PUBLIC_IP }}
          username: ${{ env.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY_PRIVATE }}
          passphrase: ${{ secrets.EC2_SSH_KEY_PASSPHRASE }}
          port: ${{ env.SSH_PORT }}  # Specify the custom port

      - name: Test SSH connection
        run: ssh -i ~/.ssh/id_rsa -p ${{ env.SSH_PORT }} ${{ env.EC2_USER }}@${{ env.PUBLIC_IP }} "echo SSH connection successful"
