name: Deploy Portfolio to EC2

on:
  push:
    branches:
      - main

env:
  PUBLIC_IP: 3.110.77.19
  EC2_USER: ubuntu
  SSH_PORT: 1243

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add EC2 server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ env.SSH_PORT }} ${{ env.PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Configure SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY_PRIVATE }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Test SSH connection
        run: ssh -i ~/.ssh/id_rsa -p ${{ env.SSH_PORT }} ${{ env.EC2_USER }}@${{ env.PUBLIC_IP }} "echo SSH connection successful"
