name: Deploy enzodevops.online Portfolio to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_EIP }}  # Use EC2 Elastic IP
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # Reference SSH private key
          port: 1243  # Custom SSH port
          source: "./*"  # All files in the repository
          target: "/var/www/html/" 

      - name: Add SSH public key to authorized keys
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_EIP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 1243
          script: |
            sudo mkdir -p /home/${{ secrets.EC2_USER }}/.ssh
            sudo chmod 700 /home/${{ secrets.EC2_USER }}/.ssh
            echo "${{ secrets.EC2_SSH_PUBLIC_KEY }}" >> /home/${{ secrets.EC2_USER }}/.ssh/authorized_keys
            sudo chmod 600 /home/${{ secrets.EC2_USER }}/.ssh/authorized_keys

      - name: Restart Apache on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_EIP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 1243
          script: |
            sudo systemctl restart apache2
